version: "3"
services:
  platform:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: platform-container
    image: backend:latest
    hostname: localhost
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo-container
    image: mongo:latest
    hostname: localhost
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:
  db:
